name: constopt
channels:
 - pytorch
dependencies:
 - python=3
 - numpy
 - pandas
 - pytorch
 - cudatoolkit
 - jupyter
 - torchvision
 - pylint
 - pytest
 - rope
 - pip
 - pip:
   - tables
   - dill
   - copt
   - advertorch
   - easydict